export default Object.freeze({
	USER: "user",
	ROLE: "role",
	CATEGORY: "category",
	PROBLEM_STATUS: "problem_status",
	PROFILE: "profile",
	DIFFICULTY: "difficulty",
	PROBLEM: "problem",
	CONTRIBUTOR: "contributor",
	PROGRESS: "progress",
	SUBMISSION: "submission",
	RATING: "rating",
	DEDUCTION_TYPE: "deduction_type",
	PROBLEM_DEDUCTION: "problem_deduction",
	AUDIT: "audit",
	MAZE_REQUIREMENT: "maze_requirement",
	LOCATION: "location",
});